apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    # Says create an ingress controller based on the nginx project
    kubernetes.io/ingress.class: nginx
    # Configure /api to route to / on server so we don't have to write /api all over our express app
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    # hey k8s, you should be expecting to receive a certificate from lets encrypt
    cert-manager.io/cluster-issuer: 'letsencrypt-prod'
    # TODO: Switch to true for PROD
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
spec:
  tls:
    - hosts:
        - helladiversity.com
        - www.helladiversity.com
      # from certificate file
      secretName: helladiversity-com
  rules:
    - host: helladiversity.com
      http:
        # if anybody goes to path /, send them to the client, if request goes to /api/, send it to the server
        paths:
          - path: /?(.*)
            backend:
              serviceName: client-cluster-ip-service
              servicePort: 3000
          - path: /api/?(.*)
            backend:
              serviceName: server-cluster-ip-service
              servicePort: 5000
    - host: www.helladiversity.com
      http:
        # if anybody goes to path /, send them to the client, if request goes to /api/, send it to the server
        paths:
          - path: /?(.*)
            backend:
              serviceName: client-cluster-ip-service
              servicePort: 3000
          - path: /api/?(.*)
            backend:
              serviceName: server-cluster-ip-service
              servicePort: 5000