# issuer
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme: 
    server: https://acme-v02.api.letsencrypt.org/directory
    email: 'mikey.aburamadan@gmail.com'
    # LetsEncrypt sends over this secret to kubernetes just to verify we own domain. we dont actually use it but k8s does
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}
      
    